#!/usr/bin/python3

import sys
sys.path[0:0] = (".", "../distkv", "../trio", "../distowfs", "../distwago", "../wago",".", "../asyncactor","../distinv","../asyncclick","../anyio/src")

import trio
import traceback
from outcome import Error

from moat.mqtt.scripts.broker_script import main
main()


